name: build

on:
  push:
  workflow_dispatch:
  schedule:
    # rebuild when static values need updating
    - cron: "0 0 1 1 *"
    - cron: "0 0 15 1 *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nodejs LTS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Build Site
        shell: bash
        run: |
          GIT_SHA=$(git rev-parse HEAD) make build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v7
        with:
          name: release
          path: build/
